# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "XKFAXIW.OHB38790"
user = "jayshreemankape"
password = "eMvgH8dqhybS9W8"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "HARMONIZED"
